server:
  port: 8081

spring:
  mail:
    host: smtp.poczta.onet.pl
    port: 465
    username: przykladowe991122@op.pl
    password: Cosima44#
    properties:
      mail.smtp.ssl.enable: true
      smtp:
        auth: true
